export appReducer from './appReducer';
export createRouteReducer from './createRouteReducer';
export createVerticeReducer from './createVerticeReducer';
export flashMessagesReducer from './flashMessagesReducer';
export routesReducer from './routesReducer';
export selectedBucketReducer from './selectedBucketReducer';
export userReducer from './userReducer';
export routeDetail from './routeDetailReducer';
export inspiration from './inspirationReducer';
