const foursquare = {
   "photos":[
      {
         "id":"50f15e1de4b00ee57e0d3c09",
         "createdAt":1357995549,
         "source":{
            "name":"Foursquare for iOS",
            "url":"https://foursquare.com/download/#/iphone"
         },
         "prefix":"https://irs0.4sqi.net/img/general/",
         "suffix":"/996938_l9yMmi53BfeHS6qnkGXS5wdKhOO-yrIWvKtAzSFI6ak.jpg",
         "width":959,
         "height":717,
         "user":{
            "id":"996938",
            "firstName":"john",
            "lastName":"svendsen",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/0D4X0WLFYCWW24UT.jpg"
            }
         },
         "visibility":"public"
      },
      {
         "id":"51b37a29498e6923ef6d63fe",
         "createdAt":1370716713,
         "source":{
            "name":"Foursquare for iOS",
            "url":"https://foursquare.com/download/#/iphone"
         },
         "prefix":"https://irs1.4sqi.net/img/general/",
         "suffix":"/3274837_2upoXWi9ncOCGZN_-F8yvcyyYwb4kloNYyxZo-RAW5s.jpg",
         "width":720,
         "height":720,
         "user":{
            "id":"3274837",
            "firstName":"Monika",
            "gender":"female",
            "photo":{
               "prefix":"https://irs1.4sqi.net/img/user/",
               "suffix":"/3274837-5B4BSBBOERGCXJON.jpg"
            }
         },
         "visibility":"public"
      },
      {
         "id":"50976287e4b0928370e6ae9f",
         "createdAt":1352098439,
         "source":{
            "name":"Foursquare for iOS",
            "url":"https://foursquare.com/download/#/iphone"
         },
         "prefix":"https://irs1.4sqi.net/img/general/",
         "suffix":"/16439494_hGPTwqEbL654li178E9B0x02OoGD2ldtWqfNfnrJDAI.jpg",
         "width":720,
         "height":540,
         "user":{
            "id":"16439494",
            "firstName":"Hans Petter",
            "lastName":"Fosseng",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/N4CSJEK5XM23VEP4.jpg"
            }
         },
         "visibility":"public"
      },
      {
         "id":"5272638111d2ae893f004d4c",
         "createdAt":1383228289,
         "source":{
            "name":"Instagram",
            "url":"http://instagram.com"
         },
         "prefix":"https://irs2.4sqi.net/img/general/",
         "suffix":"/103345__tx2WQS0c4jXy_5SPgkqVM2xX-ARPnCnK4WcA4oZcp4.jpg",
         "width":640,
         "height":640,
         "user":{
            "id":"103345",
            "firstName":"Anders",
            "lastName":"Husa",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/5TMMB55IXNGKV4NJ.jpg"
            }
         },
         "visibility":"public"
      },
      {
         "id":"508c6e6ce4b032cef28b8966",
         "createdAt":1351380588,
         "source":{
            "name":"Instagram",
            "url":"http://instagram.com"
         },
         "prefix":"https://irs1.4sqi.net/img/general/",
         "suffix":"/458898_WCW4k8JVBAfqZhm0YYhbvodQtZAnHbqEgfAx1l3ZF4U.jpg",
         "width":612,
         "height":612,
         "user":{
            "id":"458898",
            "firstName":"Andreas",
            "lastName":"Schanzenbach",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/UVLKU2I4US4D3CZL.jpg"
            }
         },
         "visibility":"public"
      },
      {
         "id":"4f4a3fa9e4b045878252db73",
         "createdAt":1330266025,
         "source":{
            "name":"Foursquare for iOS",
            "url":"https://foursquare.com/download/#/iphone"
         },
         "prefix":"https://irs0.4sqi.net/img/general/",
         "suffix":"/XCkI5644iNMFZ0XmjsRZjYHSG3s8_lyVv4W-mTNhEYc.jpg",
         "width":720,
         "height":537,
         "user":{
            "id":"103345",
            "firstName":"Anders",
            "lastName":"Husa",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/5TMMB55IXNGKV4NJ.jpg"
            }
         },
         "visibility":"public"
      }
   ],
   "meta":{
      "id":"4b509820f964a520aa2827e3",
      "name":"Fuglen",
      "contact":{
         "phone":"+4722200880",
         "formattedPhone":"+47 22 20 08 80",
         "twitter":"fuglenoslo"
      },
      "location":{
         "address":"Universitetsgata 2",
         "crossStreet":"Pilestredet",
         "lat":59.917058890801314,
         "lng":10.739741921424864,
         "postalCode":"0164",
         "cc":"NO",
         "city":"Oslo",
         "state":"Oslo",
         "country":"Norge",
         "formattedAddress":[
            "Universitetsgata 2 (Pilestredet)",
            "0164 Oslo",
            "Norge"
         ]
      },
      "canonicalUrl":"https://foursquare.com/v/fuglen/4b509820f964a520aa2827e3",
      "categories":[
         {
            "id":"4bf58dd8d48988d1e0931735",
            "name":"Coffee Shop",
            "pluralName":"Coffee Shops",
            "shortName":"Coffee Shop",
            "icon":{
               "prefix":"https://ss3.4sqi.net/img/categories_v2/food/coffeeshop_",
               "suffix":".png"
            },
            "primary":true
         },
         {
            "id":"4bf58dd8d48988d16d941735",
            "name":"Café",
            "pluralName":"Cafés",
            "shortName":"Café",
            "icon":{
               "prefix":"https://ss3.4sqi.net/img/categories_v2/food/cafe_",
               "suffix":".png"
            }
         },
         {
            "id":"4bf58dd8d48988d11e941735",
            "name":"Cocktail Bar",
            "pluralName":"Cocktail Bars",
            "shortName":"Cocktail",
            "icon":{
               "prefix":"https://ss3.4sqi.net/img/categories_v2/nightlife/cocktails_",
               "suffix":".png"
            }
         }
      ],
      "verified":false,
      "stats":{
         "checkinsCount":3098,
         "usersCount":1625,
         "tipCount":101,
         "visitsCount":3989
      },
      "url":"http://www.fuglen.no",
      "price":{
         "tier":2,
         "message":"Moderate",
         "currency":"$"
      },
      "likes":{
         "count":289,
         "groups":[

         ],
         "summary":"289 Likes"
      },
      "dislike":false,
      "ok":false,
      "rating":9.5,
      "ratingSignals":373,
      "allowMenuUrlEdit":true,
      "specials":{
         "count":0,
         "items":[

         ]
      },
      "photos":{
         "count":240,
         "groups":[
            {
               "type":"venue",
               "name":"Venue photos",
               "count":240,
               "items":[
                  {
                     "id":"50f15e1de4b00ee57e0d3c09",
                     "createdAt":1357995549,
                     "source":{
                        "name":"Foursquare for iOS",
                        "url":"https://foursquare.com/download/#/iphone"
                     },
                     "prefix":"https://irs0.4sqi.net/img/general/",
                     "suffix":"/996938_l9yMmi53BfeHS6qnkGXS5wdKhOO-yrIWvKtAzSFI6ak.jpg",
                     "width":959,
                     "height":717,
                     "user":{
                        "id":"996938",
                        "firstName":"john",
                        "lastName":"svendsen",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/0D4X0WLFYCWW24UT.jpg"
                        }
                     },
                     "visibility":"public"
                  },
                  {
                     "id":"51b37a29498e6923ef6d63fe",
                     "createdAt":1370716713,
                     "source":{
                        "name":"Foursquare for iOS",
                        "url":"https://foursquare.com/download/#/iphone"
                     },
                     "prefix":"https://irs1.4sqi.net/img/general/",
                     "suffix":"/3274837_2upoXWi9ncOCGZN_-F8yvcyyYwb4kloNYyxZo-RAW5s.jpg",
                     "width":720,
                     "height":720,
                     "user":{
                        "id":"3274837",
                        "firstName":"Monika",
                        "gender":"female",
                        "photo":{
                           "prefix":"https://irs1.4sqi.net/img/user/",
                           "suffix":"/3274837-5B4BSBBOERGCXJON.jpg"
                        }
                     },
                     "visibility":"public"
                  },
                  {
                     "id":"50976287e4b0928370e6ae9f",
                     "createdAt":1352098439,
                     "source":{
                        "name":"Foursquare for iOS",
                        "url":"https://foursquare.com/download/#/iphone"
                     },
                     "prefix":"https://irs1.4sqi.net/img/general/",
                     "suffix":"/16439494_hGPTwqEbL654li178E9B0x02OoGD2ldtWqfNfnrJDAI.jpg",
                     "width":720,
                     "height":540,
                     "user":{
                        "id":"16439494",
                        "firstName":"Hans Petter",
                        "lastName":"Fosseng",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/N4CSJEK5XM23VEP4.jpg"
                        }
                     },
                     "visibility":"public"
                  },
                  {
                     "id":"5272638111d2ae893f004d4c",
                     "createdAt":1383228289,
                     "source":{
                        "name":"Instagram",
                        "url":"http://instagram.com"
                     },
                     "prefix":"https://irs2.4sqi.net/img/general/",
                     "suffix":"/103345__tx2WQS0c4jXy_5SPgkqVM2xX-ARPnCnK4WcA4oZcp4.jpg",
                     "width":640,
                     "height":640,
                     "user":{
                        "id":"103345",
                        "firstName":"Anders",
                        "lastName":"Husa",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/5TMMB55IXNGKV4NJ.jpg"
                        }
                     },
                     "visibility":"public"
                  },
                  {
                     "id":"508c6e6ce4b032cef28b8966",
                     "createdAt":1351380588,
                     "source":{
                        "name":"Instagram",
                        "url":"http://instagram.com"
                     },
                     "prefix":"https://irs1.4sqi.net/img/general/",
                     "suffix":"/458898_WCW4k8JVBAfqZhm0YYhbvodQtZAnHbqEgfAx1l3ZF4U.jpg",
                     "width":612,
                     "height":612,
                     "user":{
                        "id":"458898",
                        "firstName":"Andreas",
                        "lastName":"Schanzenbach",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/UVLKU2I4US4D3CZL.jpg"
                        }
                     },
                     "visibility":"public"
                  },
                  {
                     "id":"4f4a3fa9e4b045878252db73",
                     "createdAt":1330266025,
                     "source":{
                        "name":"Foursquare for iOS",
                        "url":"https://foursquare.com/download/#/iphone"
                     },
                     "prefix":"https://irs0.4sqi.net/img/general/",
                     "suffix":"/XCkI5644iNMFZ0XmjsRZjYHSG3s8_lyVv4W-mTNhEYc.jpg",
                     "width":720,
                     "height":537,
                     "user":{
                        "id":"103345",
                        "firstName":"Anders",
                        "lastName":"Husa",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/5TMMB55IXNGKV4NJ.jpg"
                        }
                     },
                     "visibility":"public"
                  }
               ]
            }
         ]
      },
      "reasons":{
         "count":1,
         "items":[
            {
               "summary":"Lots of people like this place",
               "type":"general",
               "reasonName":"rawLikesReason"
            }
         ]
      },
      "hereNow":{
         "count":0,
         "summary":"Nobody here",
         "groups":[

         ]
      },
      "createdAt":1263573024,
      "tips":{
         "count":101,
         "groups":[
            {
               "type":"others",
               "name":"All tips",
               "count":101,
               "items":[
                  {
                     "id":"4c7f50eea852199cd431ceaf",
                     "createdAt":1283412206,
                     "text":"Order an espresso by day or a cocktail by night and scan a qr-tag on one of the fine design items they have for sale. Experience a new way to shop in Oslo's finest lounge style coffee shop and bar.",
                     "type":"user",
                     "url":"http://www.fuglen.no/",
                     "canonicalUrl":"https://foursquare.com/item/4c7f50eea852199cd431ceaf",
                     "lang":"en",
                     "likes":{
                        "count":13,
                        "groups":[

                        ],
                        "summary":"13 Likes"
                     },
                     "logView":true,
                     "saves":{
                        "count":7,
                        "groups":[
                           {
                              "type":"others",
                              "count":3,
                              "items":[
                                 {
                                    "user":{
                                       "id":"33743072",
                                       "firstName":"Kathy",
                                       "lastName":"J",
                                       "gender":"none",
                                       "photo":{
                                          "prefix":"https://irs0.4sqi.net/img/user/",
                                          "suffix":"/33743072-EW4OK1RK1XRN5OOK.jpg"
                                       }
                                    },
                                    "sharedAt":1412122056,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"542b45c8ccd624de67af5f1f"
                                 },
                                 {
                                    "user":{
                                       "id":"13520945",
                                       "firstName":"Arto",
                                       "lastName":"Paljakka",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs2.4sqi.net/img/user/",
                                          "suffix":"/Z0XY2AVIVHLMMJYG.jpg"
                                       }
                                    },
                                    "sharedAt":1334349219,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4f888da3a75dbc9c880f0809"
                                 },
                                 {
                                    "user":{
                                       "id":"19700495",
                                       "firstName":"Johanne",
                                       "lastName":"Lundebrekke Myskja",
                                       "gender":"female",
                                       "photo":{
                                          "prefix":"https://irs3.4sqi.net/img/user/",
                                          "suffix":"/5QQ50HMKTN0XCZAV.jpg"
                                       }
                                    },
                                    "sharedAt":1326619391,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4f129aff4789363858c5df79"
                                 }
                              ]
                           }
                        ],
                        "summary":"7 Saves"
                     },
                     "user":{
                        "id":"1359140",
                        "firstName":"John",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs1.4sqi.net/img/user/",
                           "suffix":"/XJATQIERT53J5SNN.jpg"
                        }
                     }
                  },
                  {
                     "id":"4b64c14e70c603bbda2b91b4",
                     "createdAt":1264894286,
                     "text":"Very original and retro place. It's a joy to watch the barista work. I recommended the Chai Latte.",
                     "type":"user",
                     "canonicalUrl":"https://foursquare.com/item/4b64c14e70c603bbda2b91b4",
                     "lang":"en",
                     "likes":{
                        "count":10,
                        "groups":[

                        ],
                        "summary":"10 Likes"
                     },
                     "logView":true,
                     "saves":{
                        "count":8,
                        "groups":[
                           {
                              "type":"others",
                              "count":6,
                              "items":[
                                 {
                                    "user":{
                                       "id":"1562504",
                                       "firstName":"Peter",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs3.4sqi.net/img/user/",
                                          "suffix":"/1562504-TTDGWFFFVUEPCHDB"
                                       }
                                    },
                                    "sharedAt":1429272759,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"5530f8b742aec755af44e431"
                                 },
                                 {
                                    "user":{
                                       "id":"370297",
                                       "firstName":"Marius",
                                       "lastName":"Lauritsen",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs0.4sqi.net/img/user/",
                                          "suffix":"/S24XCJULGDI5PSU5.png"
                                       }
                                    },
                                    "sharedAt":1324152669,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4eecf75dac3847e1b1a439a5"
                                 },
                                 {
                                    "user":{
                                       "id":"5360419",
                                       "firstName":"Andreas",
                                       "lastName":"Viseth",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs3.4sqi.net/img/user/",
                                          "suffix":"/3ODERFS214WJCNMN.jpg"
                                       }
                                    },
                                    "sharedAt":1319039899,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4e9ef39bc3c5aca6ba0804a0"
                                 },
                                 {
                                    "user":{
                                       "id":"6869627",
                                       "firstName":"Fredrik",
                                       "lastName":"Brede",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs0.4sqi.net/img/user/",
                                          "suffix":"/MGIG03HNGJ5WAJTB.jpg"
                                       }
                                    },
                                    "sharedAt":1309491893,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4e0d42b52fb6f2ebefa246b0"
                                 },
                                 {
                                    "user":{
                                       "id":"2213511",
                                       "firstName":"Jarle",
                                       "lastName":"Heitmann",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs0.4sqi.net/img/user/",
                                          "suffix":"/CTBL2TCO0YXQWX4A.jpg"
                                       }
                                    },
                                    "sharedAt":1309477994,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4e0d0c6a2fb6f2ebef78eec3"
                                 },
                                 {
                                    "user":{
                                       "id":"330855",
                                       "firstName":"Henning",
                                       "lastName":"Støverud",
                                       "gender":"male",
                                       "photo":{
                                          "prefix":"https://irs3.4sqi.net/img/user/",
                                          "suffix":"/B2OHOYODFEI3DLJA.jpg"
                                       }
                                    },
                                    "sharedAt":1309467353,
                                    "state":"saved",
                                    "type":"tip",
                                    "id":"4e0ce2d92fb6f2ebef4ebf59"
                                 }
                              ]
                           }
                        ],
                        "summary":"8 Saves"
                     },
                     "justification":{
                        "message":"Expertise in Coffee Shops and Oslo",
                        "justificationType":"expertise"
                     },
                     "user":{
                        "id":"103345",
                        "firstName":"Anders",
                        "lastName":"Husa",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/5TMMB55IXNGKV4NJ.jpg"
                        }
                     }
                  },
                  {
                     "id":"4e8f06cf6da16fd9cf446bb5",
                     "createdAt":1317996239,
                     "text":"Koseligst og kulest i byen! I highly recommend the birdlife!!",
                     "type":"user",
                     "canonicalUrl":"https://foursquare.com/item/4e8f06cf6da16fd9cf446bb5",
                     "lang":"en",
                     "likes":{
                        "count":7,
                        "groups":[

                        ],
                        "summary":"7 Likes"
                     },
                     "logView":true,
                     "saves":{
                        "count":1,
                        "groups":[

                        ],
                        "summary":"1 Save"
                     },
                     "justification":{
                        "message":"Expertise in Oslo",
                        "justificationType":"expertise"
                     },
                     "user":{
                        "id":"13915005",
                        "firstName":"Terje",
                        "lastName":"Mjåseth",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs3.4sqi.net/img/user/",
                           "suffix":"/NEYFR4PQQWK31Y3X.jpg"
                        }
                     }
                  },
                  {
                     "id":"507eb59be4b00e30b640328f",
                     "createdAt":1350481307,
                     "text":"Anbefaler å kjøpe ein chailatte. Då får du sjå barristaen tømme teen ein halvmeter mellom to stålmugger heile sju gangar.",
                     "type":"user",
                     "canonicalUrl":"https://foursquare.com/item/507eb59be4b00e30b640328f",
                     "lang":"nn",
                     "likes":{
                        "count":5,
                        "groups":[

                        ],
                        "summary":"5 Likes"
                     },
                     "logView":true,
                     "saves":{
                        "count":0,
                        "groups":[

                        ]
                     },
                     "justification":{
                        "message":"Expertise in Oslo",
                        "justificationType":"expertise"
                     },
                     "user":{
                        "id":"124563",
                        "firstName":"Herdis",
                        "lastName":"Moldøen",
                        "gender":"female",
                        "photo":{
                           "prefix":"https://irs0.4sqi.net/img/user/",
                           "suffix":"/GD1KFVTSU20MTUFB.jpg"
                        }
                     }
                  },
                  {
                     "id":"4ba222ac70c603bb7bd594b4",
                     "createdAt":1268916908,
                     "text":"The chai is really good, so is the coffee!",
                     "type":"user",
                     "canonicalUrl":"https://foursquare.com/item/4ba222ac70c603bb7bd594b4",
                     "lang":"en",
                     "likes":{
                        "count":5,
                        "groups":[

                        ],
                        "summary":"5 Likes"
                     },
                     "logView":true,
                     "saves":{
                        "count":0,
                        "groups":[

                        ]
                     },
                     "user":{
                        "id":"593201",
                        "firstName":"Ulrik Fredrik",
                        "lastName":"Thyve",
                        "gender":"male",
                        "photo":{
                           "prefix":"https://irs0.4sqi.net/img/user/",
                           "suffix":"/blank_boy.png",
                           "default":true
                        }
                     }
                  }
               ]
            }
         ]
      },
      "tags":[

      ],
      "shortUrl":"http://4sq.com/aAfEgQ",
      "timeZone":"Europe/Oslo",
      "phrases":[
         {
            "phrase":"nice retro",
            "sample":{
               "entities":[
                  {
                     "indices":[
                        20,
                        30
                     ],
                     "type":"keyPhrase"
                  }
               ],
               "text":"Great coffee with a nice retro look. The place is gorgeous."
            },
            "count":2
         },
         {
            "phrase":"tim wendelboe",
            "sample":{
               "entities":[
                  {
                     "indices":[
                        24,
                        37
                     ],
                     "type":"keyPhrase"
                  }
               ],
               "text":"... the best beans from Tim Wendelboe and Drop Coffee."
            },
            "count":3
         },
         {
            "phrase":"great coffee",
            "sample":{
               "entities":[
                  {
                     "indices":[
                        0,
                        12
                     ],
                     "type":"keyPhrase"
                  }
               ],
               "text":"Great coffee, reasonable prices, very nice."
            },
            "count":10
         }
      ],
      "hours":{
         "status":"Open until 1:00 AM",
         "isOpen":true,
         "isLocalHoliday":false,
         "timeframes":[
            {
               "days":"Mon–Tue",
               "open":[
                  {
                     "renderedTime":"7:30 AM–7:00 PM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Wed–Thu",
               "includesToday":true,
               "open":[
                  {
                     "renderedTime":"7:30 AM–1:00 AM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Fri",
               "open":[
                  {
                     "renderedTime":"7:30 AM–3:00 AM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Sat",
               "open":[
                  {
                     "renderedTime":"10:00 AM–3:00 AM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Sun",
               "open":[
                  {
                     "renderedTime":"11:00 AM–6:00 PM"
                  }
               ],
               "segments":[

               ]
            }
         ]
      },
      "popular":{
         "status":"Likely open",
         "isOpen":true,
         "isLocalHoliday":false,
         "timeframes":[
            {
               "days":"Today",
               "includesToday":true,
               "open":[
                  {
                     "renderedTime":"9:00 AM–10:00 AM"
                  },
                  {
                     "renderedTime":"Noon–6:00 PM"
                  },
                  {
                     "renderedTime":"8:00 PM–10:00 PM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Fri",
               "open":[
                  {
                     "renderedTime":"8:00 AM–9:00 AM"
                  },
                  {
                     "renderedTime":"1:00 PM–1:00 AM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Sat",
               "open":[
                  {
                     "renderedTime":"11:00 AM–1:00 AM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Sun",
               "open":[
                  {
                     "renderedTime":"11:00 AM–6:00 PM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Mon",
               "open":[
                  {
                     "renderedTime":"Noon–6:00 PM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Tue",
               "open":[
                  {
                     "renderedTime":"8:00 AM–11:00 AM"
                  },
                  {
                     "renderedTime":"1:00 PM–7:00 PM"
                  }
               ],
               "segments":[

               ]
            },
            {
               "days":"Wed",
               "open":[
                  {
                     "renderedTime":"8:00 AM–9:00 AM"
                  },
                  {
                     "renderedTime":"1:00 PM–10:00 PM"
                  }
               ],
               "segments":[

               ]
            }
         ]
      },
      "pageUpdates":{
         "count":0,
         "items":[

         ]
      },
      "inbox":{
         "count":0,
         "items":[

         ]
      },
      "venueChains":[

      ],
      "attributes":{
         "groups":[
            {
               "type":"price",
               "name":"Price",
               "summary":"$$",
               "count":1,
               "items":[
                  {
                     "displayName":"Price",
                     "displayValue":"$$",
                     "priceTier":2
                  }
               ]
            },
            {
               "type":"reservations",
               "name":"Reservations",
               "count":3,
               "items":[
                  {
                     "displayName":"Reservations",
                     "displayValue":"No"
                  }
               ]
            },
            {
               "type":"payments",
               "name":"Credit Cards",
               "summary":"Credit Cards",
               "count":5,
               "items":[
                  {
                     "displayName":"Credit Cards",
                     "displayValue":"Yes"
                  }
               ]
            },
            {
               "type":"outdoorSeating",
               "name":"Outdoor Seating",
               "summary":"Outdoor Seating",
               "count":1,
               "items":[
                  {
                     "displayName":"Outdoor Seating",
                     "displayValue":"Yes"
                  }
               ]
            },
            {
               "type":"wifi",
               "name":"Wi-Fi",
               "summary":"Wi-Fi",
               "count":1,
               "items":[
                  {
                     "displayName":"Wi-Fi",
                     "displayValue":"Yes"
                  }
               ]
            },
            {
               "type":"serves",
               "name":"Menus",
               "summary":"Dinner, Breakfast & more",
               "count":8,
               "items":[
                  {
                     "displayName":"Breakfast",
                     "displayValue":"Breakfast"
                  },
                  {
                     "displayName":"Brunch",
                     "displayValue":"Brunch"
                  },
                  {
                     "displayName":"Lunch",
                     "displayValue":"Lunch"
                  },
                  {
                     "displayName":"Dinner",
                     "displayValue":"Dinner"
                  }
               ]
            },
            {
               "type":"drinks",
               "name":"Drinks",
               "summary":"Beer & Cocktails",
               "count":5,
               "items":[
                  {
                     "displayName":"Beer",
                     "displayValue":"Beer"
                  },
                  {
                     "displayName":"Cocktails",
                     "displayValue":"Cocktails"
                  }
               ]
            },
            {
               "type":"diningOptions",
               "name":"Dining Options",
               "summary":"Delivery",
               "count":5,
               "items":[
                  {
                     "displayName":"Delivery",
                     "displayValue":"Delivery"
                  }
               ]
            }
         ]
      },
      "bestPhoto":{
         "id":"50f15e1de4b00ee57e0d3c09",
         "createdAt":1357995549,
         "source":{
            "name":"Foursquare for iOS",
            "url":"https://foursquare.com/download/#/iphone"
         },
         "prefix":"https://irs0.4sqi.net/img/general/",
         "suffix":"/996938_l9yMmi53BfeHS6qnkGXS5wdKhOO-yrIWvKtAzSFI6ak.jpg",
         "width":959,
         "height":717,
         "visibility":"public"
      }
   },
   "tips":[
      {
         "id":"4c7f50eea852199cd431ceaf",
         "createdAt":1283412206,
         "text":"Order an espresso by day or a cocktail by night and scan a qr-tag on one of the fine design items they have for sale. Experience a new way to shop in Oslo's finest lounge style coffee shop and bar.",
         "type":"user",
         "url":"http://www.fuglen.no/",
         "canonicalUrl":"https://foursquare.com/item/4c7f50eea852199cd431ceaf",
         "lang":"en",
         "likes":{
            "count":13,
            "groups":[

            ],
            "summary":"13 Likes"
         },
         "logView":true,
         "saves":{
            "count":7,
            "groups":[
               {
                  "type":"others",
                  "count":3,
                  "items":[
                     {
                        "user":{
                           "id":"33743072",
                           "firstName":"Kathy",
                           "lastName":"J",
                           "gender":"none",
                           "photo":{
                              "prefix":"https://irs0.4sqi.net/img/user/",
                              "suffix":"/33743072-EW4OK1RK1XRN5OOK.jpg"
                           }
                        },
                        "sharedAt":1412122056,
                        "state":"saved",
                        "type":"tip",
                        "id":"542b45c8ccd624de67af5f1f"
                     },
                     {
                        "user":{
                           "id":"13520945",
                           "firstName":"Arto",
                           "lastName":"Paljakka",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs2.4sqi.net/img/user/",
                              "suffix":"/Z0XY2AVIVHLMMJYG.jpg"
                           }
                        },
                        "sharedAt":1334349219,
                        "state":"saved",
                        "type":"tip",
                        "id":"4f888da3a75dbc9c880f0809"
                     },
                     {
                        "user":{
                           "id":"19700495",
                           "firstName":"Johanne",
                           "lastName":"Lundebrekke Myskja",
                           "gender":"female",
                           "photo":{
                              "prefix":"https://irs3.4sqi.net/img/user/",
                              "suffix":"/5QQ50HMKTN0XCZAV.jpg"
                           }
                        },
                        "sharedAt":1326619391,
                        "state":"saved",
                        "type":"tip",
                        "id":"4f129aff4789363858c5df79"
                     }
                  ]
               }
            ],
            "summary":"7 Saves"
         },
         "user":{
            "id":"1359140",
            "firstName":"John",
            "gender":"male",
            "photo":{
               "prefix":"https://irs1.4sqi.net/img/user/",
               "suffix":"/XJATQIERT53J5SNN.jpg"
            }
         }
      },
      {
         "id":"4b64c14e70c603bbda2b91b4",
         "createdAt":1264894286,
         "text":"Very original and retro place. It's a joy to watch the barista work. I recommended the Chai Latte.",
         "type":"user",
         "canonicalUrl":"https://foursquare.com/item/4b64c14e70c603bbda2b91b4",
         "lang":"en",
         "likes":{
            "count":10,
            "groups":[

            ],
            "summary":"10 Likes"
         },
         "logView":true,
         "saves":{
            "count":8,
            "groups":[
               {
                  "type":"others",
                  "count":6,
                  "items":[
                     {
                        "user":{
                           "id":"1562504",
                           "firstName":"Peter",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs3.4sqi.net/img/user/",
                              "suffix":"/1562504-TTDGWFFFVUEPCHDB"
                           }
                        },
                        "sharedAt":1429272759,
                        "state":"saved",
                        "type":"tip",
                        "id":"5530f8b742aec755af44e431"
                     },
                     {
                        "user":{
                           "id":"370297",
                           "firstName":"Marius",
                           "lastName":"Lauritsen",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs0.4sqi.net/img/user/",
                              "suffix":"/S24XCJULGDI5PSU5.png"
                           }
                        },
                        "sharedAt":1324152669,
                        "state":"saved",
                        "type":"tip",
                        "id":"4eecf75dac3847e1b1a439a5"
                     },
                     {
                        "user":{
                           "id":"5360419",
                           "firstName":"Andreas",
                           "lastName":"Viseth",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs3.4sqi.net/img/user/",
                              "suffix":"/3ODERFS214WJCNMN.jpg"
                           }
                        },
                        "sharedAt":1319039899,
                        "state":"saved",
                        "type":"tip",
                        "id":"4e9ef39bc3c5aca6ba0804a0"
                     },
                     {
                        "user":{
                           "id":"6869627",
                           "firstName":"Fredrik",
                           "lastName":"Brede",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs0.4sqi.net/img/user/",
                              "suffix":"/MGIG03HNGJ5WAJTB.jpg"
                           }
                        },
                        "sharedAt":1309491893,
                        "state":"saved",
                        "type":"tip",
                        "id":"4e0d42b52fb6f2ebefa246b0"
                     },
                     {
                        "user":{
                           "id":"2213511",
                           "firstName":"Jarle",
                           "lastName":"Heitmann",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs0.4sqi.net/img/user/",
                              "suffix":"/CTBL2TCO0YXQWX4A.jpg"
                           }
                        },
                        "sharedAt":1309477994,
                        "state":"saved",
                        "type":"tip",
                        "id":"4e0d0c6a2fb6f2ebef78eec3"
                     },
                     {
                        "user":{
                           "id":"330855",
                           "firstName":"Henning",
                           "lastName":"Støverud",
                           "gender":"male",
                           "photo":{
                              "prefix":"https://irs3.4sqi.net/img/user/",
                              "suffix":"/B2OHOYODFEI3DLJA.jpg"
                           }
                        },
                        "sharedAt":1309467353,
                        "state":"saved",
                        "type":"tip",
                        "id":"4e0ce2d92fb6f2ebef4ebf59"
                     }
                  ]
               }
            ],
            "summary":"8 Saves"
         },
         "justification":{
            "message":"Expertise in Coffee Shops and Oslo",
            "justificationType":"expertise"
         },
         "user":{
            "id":"103345",
            "firstName":"Anders",
            "lastName":"Husa",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/5TMMB55IXNGKV4NJ.jpg"
            }
         }
      },
      {
         "id":"4e8f06cf6da16fd9cf446bb5",
         "createdAt":1317996239,
         "text":"Koseligst og kulest i byen! I highly recommend the birdlife!!",
         "type":"user",
         "canonicalUrl":"https://foursquare.com/item/4e8f06cf6da16fd9cf446bb5",
         "lang":"en",
         "likes":{
            "count":7,
            "groups":[

            ],
            "summary":"7 Likes"
         },
         "logView":true,
         "saves":{
            "count":1,
            "groups":[

            ],
            "summary":"1 Save"
         },
         "justification":{
            "message":"Expertise in Oslo",
            "justificationType":"expertise"
         },
         "user":{
            "id":"13915005",
            "firstName":"Terje",
            "lastName":"Mjåseth",
            "gender":"male",
            "photo":{
               "prefix":"https://irs3.4sqi.net/img/user/",
               "suffix":"/NEYFR4PQQWK31Y3X.jpg"
            }
         }
      },
      {
         "id":"507eb59be4b00e30b640328f",
         "createdAt":1350481307,
         "text":"Anbefaler å kjøpe ein chailatte. Då får du sjå barristaen tømme teen ein halvmeter mellom to stålmugger heile sju gangar.",
         "type":"user",
         "canonicalUrl":"https://foursquare.com/item/507eb59be4b00e30b640328f",
         "lang":"nn",
         "likes":{
            "count":5,
            "groups":[

            ],
            "summary":"5 Likes"
         },
         "logView":true,
         "saves":{
            "count":0,
            "groups":[

            ]
         },
         "justification":{
            "message":"Expertise in Oslo",
            "justificationType":"expertise"
         },
         "user":{
            "id":"124563",
            "firstName":"Herdis",
            "lastName":"Moldøen",
            "gender":"female",
            "photo":{
               "prefix":"https://irs0.4sqi.net/img/user/",
               "suffix":"/GD1KFVTSU20MTUFB.jpg"
            }
         }
      },
      {
         "id":"4ba222ac70c603bb7bd594b4",
         "createdAt":1268916908,
         "text":"The chai is really good, so is the coffee!",
         "type":"user",
         "canonicalUrl":"https://foursquare.com/item/4ba222ac70c603bb7bd594b4",
         "lang":"en",
         "likes":{
            "count":5,
            "groups":[

            ],
            "summary":"5 Likes"
         },
         "logView":true,
         "saves":{
            "count":0,
            "groups":[

            ]
         },
         "user":{
            "id":"593201",
            "firstName":"Ulrik Fredrik",
            "lastName":"Thyve",
            "gender":"male",
            "photo":{
               "prefix":"https://irs0.4sqi.net/img/user/",
               "suffix":"/blank_boy.png",
               "default":true
            }
         }
      }
   ]
}
export default foursquare;
